name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Жестко сбрасываем системные пути, чтобы билд не ломался о чужие NDK
    env:
      ANDROID_NDK_ROOT: ""
      ANDROID_HOME: ""

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-dev libsqlite3-dev zlib1g-dev openjdk-17-jdk zip unzip
          pip install --upgrade pip
          pip install buildozer "Cython<3.0" virtualenv

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
